### ISSUE TITLE
下载源支持配置BiliBiliSearch

### ISSUE THREAD

**Issue by hanxi** [hanxi/xiaomusic#12]
目前默认用的YouTube搜索下载，改成可以配置的。

**Comment by hanxi** [comment]
等这个 bug 修复后再接入，国内用户就可以不配置代理使用了。 https://github.com/yt-dlp/yt-dlp/issues/5083

**Comment by hanxi** [comment]
最新版本已经支持

**Comment by hanxi** [comment]
这样配置即可，国内可以不用代理了。

```yaml
version: '3'

services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./music:/app/music
    environment:
      MI_USER: '小米账号'
      MI_PASS: '小米密码'
      MI_DID: 00000
      MI_HARDWARE: 'L07A'
      XIAOMUSIC_SEARCH: 'bilisearch:'
      XIAOMUSIC_HOSTNAME: '192.168.2.5'
```
