### ISSUE TITLE
能增加  PUID变量

### ISSUE THREAD

**Issue by gldl137** [hanxi/xiaomusic#146]
能增加 PUID和PGID的权限吗，unraid下载的音乐不同用户id不好处理

**Comment by hanxi** [comment]
试试下面两种办法，看看能不能解决。

1. 使用 docker run 命令： 你可以在运行容器时使用 --user 参数指定用户。例如：

    docker run -u <user>:<group> <image_name> <command>

例如，指定用户 demo_user 和组 group1：

    docker run --user=demo_user:group1 <image_name> <command>


2. 通过 docker-compose 指定用户： 在 docker-compose.yml 文件中，可以使用 user 字段来指定用户。例如：

```
version: '3'
services:
  app:
    image: myapp:latest
    user: "1000:1000"
```
