### ISSUE TITLE
LX06不能播放

### ISSUE THREAD

**Issue by mensylisir** [hanxi/xiaomusic#258]
### docker-compose.yml如下
```
services:
  xiaomusic-ciwo:
    image: m.daocloud.io/docker.io/hanxi/xiaomusic
    container_name: xiaomusic-ciwo
    restart: unless-stopped
    environment:
      MI_USER: '123'
      MI_PASS: '123'
      MI_DID: 570068003
      MI_HARDWARE: 'LX06'  #小米音箱的型号，默认L07A
      XIAOMUSIC_SEARCH: 'ytsearch:'   #'bilisearch:'表示B站，'ytsearch:' 表示油管
      XIAOMUSIC_HOSTNAME: '192.168.31.34'   #宿主机IP
      XIAOMUSIC_PROXY: 'http://192.168.31.34:7890'
      XIAOMUSIC_PORT: 30002
      XIAOMUSIC_VERBOSE: true
    ports:
      - 30002:30002
    volumes:
      - /mydata/music/:/app/music
      - ./conf/ciwo:/app/conf
```

### 日志如下，看不出来什么有用的信息
2024-11-11 12:28:03] [0.3.46] [DEBUG] xiaomusic.py:1058: searchmusic. name:周杰伦 qi search_list:[]
[12:28:03] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /searchmusic?name=%E5%91%A8%E6%9D%B0%E4%BC%A6%20qi HTTP/1.1" 200
[2024-11-11 12:28:04] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:04] [0.3.46] [DEBUG] xiaomusic.py:1058: searchmusic. name:周杰伦 qi'li'xiang search_list:[]
[12:28:04] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /searchmusic?name=%E5%91%A8%E6%9D%B0%E4%BC%A6%20qi%27li%27xiang HTTP/1.1" 200
[2024-11-11 12:28:05] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:05] [0.3.46] [DEBUG] xiaomusic.py:1058: searchmusic. name:周杰伦 七里香 search_list:[]
[12:28:05] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /searchmusic?name=%E5%91%A8%E6%9D%B0%E4%BC%A6%20%E4%B8%83%E9%87%8C%E9%A6%99 HTTP/1.1" 200
[2024-11-11 12:28:05] [0.3.46] [INFO] httpserver.py:212: docmd. did:570068003 cmd:播放歌曲周杰伦 七里香|
[12:28:05] [0.3.46] [INFO] 192.168.31.32:6858 - "POST /cmd HTTP/1.1" 200
[2024-11-11 12:28:06] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[12:28:06] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /playingmusic?did=570068003 HTTP/1.1" 200
[2024-11-11 12:28:07] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:08] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:09] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[12:28:09] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /playingmusic?did=570068003 HTTP/1.1" 200
[2024-11-11 12:28:10] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:11] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[2024-11-11 12:28:12] [0.3.46] [DEBUG] xiaomusic.py:173: Listening new message, timestamp: {}
[12:28:12] [0.3.46] [INFO] 192.168.31.32:6858 - "GET /playingmusic?did=570068003 HTTP/1.1" 200
