### ISSUE TITLE
播放歌曲口令支持模糊搜索

### ISSUE THREAD

**Issue by hanxi** [hanxi/xiaomusic#52]
做成可配置选项，口令为播放歌曲+搜索词，播放匹配的第一个。

**Comment by hanxi** [comment]
v0.1.77 版本支持模糊搜索

**Comment by hanxi** [comment]
模糊匹配默认打开，如果想关闭可以把 XIAOMUSIC_ENABLE_FUZZY_MATCH 设为 false。如下:
```yaml
services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./music:/app/music
    environment:
      MI_USER: '小米账号'
      MI_PASS: '小米密码'
      XIAOMUSIC_ENABLE_FUZZY_MATCH : 'false'
      XIAOMUSIC_HOSTNAME: 'docker 主机 ip'
```

如果想要修改匹配阈值，可以设置 XIAOMUSIC_FUZZY_MATCH_CUTOFF ，这个值默认为 0.6，可以配0到1直接的小数，越小越模糊，越大越精准。比如：
```yaml
services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./music:/app/music
    environment:
      MI_USER: '小米账号'
      MI_PASS: '小米密码'
      XIAOMUSIC_FUZZY_MATCH_CUTOFF : '0.3'
      XIAOMUSIC_HOSTNAME: 'docker 主机 ip'
```
