### ISSUE TITLE
建议配置文件目录和下载目录分开

### ISSUE THREAD

**Issue by huluohu** [hanxi/xiaomusic#74]
开发者你好，一般来说，实用NAS，音乐是单独放在一个媒体库的，目前setting.json和下载音乐是放在同一个目录的，混在一起不便于管理，建议分成两个目录。

当然，实用上没啥影响。

**Comment by hanxi** [comment]
建议不错，当初这样实现是为了少映射一个目录进docker里做持久化，后面考虑加个可以配置目录。

**Comment by losingrose** [comment]
MI_HARDWARE='X08E'

**Comment by hanxi** [comment]
配置示例:

```yaml
services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./music:/app/music
      - ./conf:/app/conf
    environment:
      MI_USER: '小米账号'
      MI_PASS: '小米密码'
      XIAOMUSIC_CONF_PATH: /app/conf
      XIAOMUSIC_HOSTNAME: 'docker 主机 ip'
```
这样就会把 setting.json 文件保存到容器中的 /app/conf 目录和 docker 主机的 ./conf 目录。
